---
title: eDNA analysis Everglades
output: md_document
editor_options: 
  chunk_output_type: console
---

# eDNA analysis Everglades

This notebook contains an exploratory data analysis for Everglades National Park. Images and tables are exported to the `report`` folder.

```{r setup, include=FALSE}
knitr::opts_chunk$set(dpi=300)
library(ggplot2)
library(dplyr)
library(purrr)
library(stringr)
library(xtable)
library(rredlist)
library(sf)
library(ggsvg)
library(ggrepel)
```

## Read dataset

```{r message=FALSE, warning=FALSE}
dna_files <- list.files("edna-results/data", "*DNADerivedData*", full.names = TRUE)
dna_files <- dna_files[str_detect(dna_files, "everglades")]
occurrence_files <- list.files("edna-results/data", "*Occurrence*", full.names = TRUE)
occurrence_files <- occurrence_files[str_detect(occurrence_files, "everglades")]

dna <- map(dna_files, read.table, sep = "\t", quote = "", header = TRUE) %>%
  bind_rows() %>%
  mutate_if(is.character, na_if, "")

occurrence <- map(occurrence_files, read.table, sep = "\t", quote = "", header = TRUE) %>%
  bind_rows() %>%
  mutate_if(is.character, na_if, "") %>%
  mutate(species = ifelse(taxonRank == "species", scientificName, NA)) %>%
  left_join(dna, by = "occurrenceID") %>%
  filter(higherGeography == "Everglades National Park")
```

## Overall statistics

```{r message=FALSE, warning=FALSE, fig.width=10, fig.height=5}
sample_volumes <- occurrence %>%
  distinct(materialSampleID, sampleSize) %>%
  mutate(sampleSize = as.integer(sampleSize))
  
sample_stats <- occurrence %>%
  group_by(locality, materialSampleID) %>%
  summarize(reads = sum(organismQuantity), species = n_distinct(na.omit(species)), asvs = n_distinct(DNA_sequence)) %>%
  left_join(sample_volumes, by = "materialSampleID")

stats <- occurrence %>%
  summarize(reads = sum(organismQuantity), species = n_distinct(na.omit(species)), asvs = n_distinct(DNA_sequence))

marker_stats <- occurrence %>%
  group_by(pcr_primer_name_forward) %>%
  summarize(reads = sum(organismQuantity), species = n_distinct(na.omit(species)), asvs = n())

print(xtable(sample_stats, type = "latex"), file = "report/sample_stats.tex", include.rownames = FALSE, tabular.environment = "longtable", floating = FALSE)

print(xtable(stats, type = "latex"), file = "report/stats.tex", include.rownames = FALSE, tabular.environment = "longtable", floating = FALSE)
```

## Sampling location map

```{r message=FALSE, warning=FALSE, fig.width=10, fig.height=5}
everglades <- read_sf("map/everglades.gpkg")

sites <- occurrence %>%
  select(decimalLongitude, decimalLatitude, locality) %>%
  distinct() %>%
  st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs = 4326, remove = FALSE)

ggplot() +
  geom_sf(data = everglades %>% st_transform(4326), fill = NA, color = alpha("#237d2a", 0.5), lwd = 2) +
  geom_sf(data = st_as_sfc("POLYGON ((-82 26, -80 26, -80 24.8, -82 24.8, -82 26))", crs = 4326), fill = NA, color = NA) +
  geom_point(data = sites, aes(decimalLongitude, decimalLatitude), color = "#e3007d", shape = 21, stroke = 2, size = 3) +
  geom_text_repel(data = sites, aes(decimalLongitude, decimalLatitude, label = locality), size = 5, box.padding = 2, point.padding = 1, force_pull = 0.1) +
  landr::geom_landr(after = 0, fill = "#f2f2f2") +
  theme_void()

ggsave("report/map.png", scale = 1.2, bg = "white", width = 10, height = 7)
```

## Species list

```{r message=FALSE, warning=FALSE, fig.width=10, fig.height=5}
species <- occurrence %>%
  filter(!is.na(species)) %>%
  group_by(phylum, class, order, family, genus, species) %>%
  summarize(asvs = n(), reads = sum(organismQuantity)) %>%
  ungroup()

redlist <- data.frame()
page <- 0
while (TRUE) {
  res <- rl_sp(page, key = "a936c4f78881e79a326e73c4f97f34a6e7d8f9f9e84342bff73c3ceda14992b9")$result
  if (length(res) == 0) {
    break
  }
  redlist <- bind_rows(redlist, res)
  page <- page + 1
}
redlist <- redlist %>%
  filter(is.na(population)) %>%
  filter(category %in% c("CR", "EN", "EW", "EX", "VU", "NT")) %>%
  select(species = scientific_name, category)

species <- species %>%
    left_join(redlist, by = "species")

print(xtable(species %>% select(phylum, class, family, species, category), type = "latex"), file = "report/species.tex", include.rownames = FALSE, tabular.environment = "longtable", floating = FALSE)
```

## Taxonomic tree with number of species and reads (top phyla)

```{r message=FALSE, warning=FALSE, fig.width=10, fig.height=5}
library(data.tree)
library(tidyr)
library(ggtree)
library(ggtreeExtra) # BiocManager::install("ggtreeExtra")
library(phylobase)

df <- species %>%
  group_by(phylum, class, order, family) %>%
  summarize(species = n(), asvs = sum(asvs), reads = sum(reads)) %>%
  mutate(domain = "Eukaryota") %>%
  ungroup()

top_phyla <- df %>%
  group_by(phylum) %>%
  summarize(species = sum(species)) %>%
  arrange(desc(species)) %>%
  head(10) %>%
  pull(phylum)

df_subset <- df %>%
  filter(phylum %in% top_phyla)

# marker stats

marker_stats <- occurrence %>%
  group_by(family, pcr_primer_name_forward) %>%
  summarize(reads = sum(organismQuantity)) %>%
  mutate(pcr_primer_name_forward = factor(pcr_primer_name_forward))

ggplot() + geom_point(data = marker_stats, aes(family, pcr_primer_name_forward, size = reads))

# dataframe to tree, look into alternatives

paths <- df_subset %>%
  unite(path, c(domain, phylum, class, order, family), sep = ";")
nwk <- ToNewick(as.Node(paths, pathName = "path", mode = "table", pathDelimiter = ";"))
writeLines(nwk, "tree.nwk")
tree <- read.tree("tree.nwk")

# add data to tree

# tree_data <- df %>%
#   select(species)
# row.names(tree_data) <- df$family
# tree_with_data <- phylo4d(tree, tip.data = tree_data)

# plot

ggtree(tree, layout = "circular") +
  geom_nodepoint() +
  geom_fruit(data = df_subset, aes(x = species, y = family, fill = phylum), geom = geom_bar, stat = "identity") +
  geom_fruit(data = marker_stats, aes(y = family, x = pcr_primer_name_forward, size = reads, color = pcr_primer_name_forward), geom = geom_point, name = "marker") +
  geom_tiplab(size = 3, offset = 60) +
  scale_fill_brewer(palette = "Spectral") +
  scale_color_brewer(palette = "Paired") +
  theme(plot.title = element_text(hjust = 0.5)) +
  guides(color = guide_legend(title = "marker"))

ggsave("report/tree.png", scale = 1.2, width=10, height=9)
```
